---
title: "Adminportal"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    logo: ../oge_logo/icon_scaled.jpg
    favicon: ../oge_logo/icon_scaled.jpg
    theme: cerulean
    css: ../css/dashboard.css
runtime: shiny
---

```{r setup, include=FALSE}
library(shiny)
library(shinyjs)
shiny::addResourcePath("data", file.path(dirname(getwd()), "data"))
shiny::addResourcePath("oge_logo", file.path(dirname(getwd()), "oge_logo"))
shiny::addResourcePath("css", file.path(dirname(getwd()), "css"))
```

Neue Einträge
=========================

```{r}
outputDir <- "../data/user_input"

saveData <- function(data) {
  if(!dir.exists(outputDir)){
    dir.create(outputDir)
  }
  data <- t(data)
  # Create a unique file name
  fileName <- sprintf("Edits_%s_%s.csv", as.integer(Sys.time()), digest::digest(data))
  # Write the file to the local system
  write.csv(
    x = data,
    file = file.path(outputDir, fileName),
    row.names = FALSE, quote = TRUE
  )
}

loadData <- function() {
  # Read all the files into a list
  files <- list.files(outputDir, full.names = TRUE)
  if(length(files)==0)
    return(NULL)
  data <- lapply(files, read.csv, stringsAsFactors = FALSE)
  # Concatenate all data together into one data.frame
  data <- do.call(rbind, data)
  data
}

  access <- FALSE

  ui <- fluidPage(useShinyjs(),
    div(id = "mx",
      passwordInput("password", "Password:"),
      actionButton("go", "Go")),
      verbatimTextOutput("value"),
      h1(id="heading","Offene Anfragen:", hidden = TRUE)
      ,DT::dataTableOutput("responses", width = 300)

  )
  server <- function(input, output) {
    output$value <- renderText({
      req(input$go)
      pwd <- isolate(input$password)
      if(pwd == "match"){
        hide(id = "mx",anim = TRUE)
        access <<- TRUE
         output$responses <- DT::renderDataTable({loadData()})
          show("heading")
        return("Willkommen!")
      }else
        return("Kein Zugang!")
    })


  }
  shinyApp(ui, server)


```

